spring:
  application:
    name: ${APP_NAME:notification-system}

  threads:
    virtual:
      enabled: ${VIRTUAL_THREADS_ENABLED:false}

  main:
    keep-alive: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/notification}
    username: ${SPRING_DATASOURCE_USERNAME:notification}
    password: ${SPRING_DATASOURCE_PASSWORD:notification}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:notification}
    password: ${SPRING_RABBITMQ_PASSWORD:notification}
    listener:
      simple:
        prefetch: ${RABBITMQ_PREFETCH:250}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}

    distribution:
      percentiles-histogram:
        http.server.requests: true