spring:
  application:
    name: ${APP_NAME:system-design-template}

  threads:
    virtual:
      enabled: ${VIRTUAL_THREADS_ENABLED:false}

  main:
    keep-alive: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}

    distribution:
      percentiles-histogram:
        http.server.requests: true