spring:
  application:
    name: ${APP_NAME:notification-system}

  threads:
    virtual:
      enabled: ${VIRTUAL_THREADS_ENABLED:false}

  main:
    keep-alive: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/notification}
    username: ${SPRING_DATASOURCE_USERNAME:notification}
    password: ${SPRING_DATASOURCE_PASSWORD:notification}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:notification}
    password: ${SPRING_RABBITMQ_PASSWORD:notification}
    listener:
      simple:
        prefetch: ${RABBITMQ_PREFETCH:250}
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      connect-timeout: 300ms
      timeout: 300ms

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}

    distribution:
      percentiles-histogram:
        http.server.requests: true

mock:
  provider:
    force-failure: ${MOCK_PROVIDER_FORCE_FAILURE:false}
    fail-first-attempts: ${MOCK_PROVIDER_FAIL_FIRST_ATTEMPTS:0}

outbox:
  publish-interval-ms: ${OUTBOX_PUBLISH_INTERVAL_MS:1000}


notification:
  rate-limit:
    push: ${PUSH_RATE_LIMIT:1000}
    sms: ${SMS_RATE_LIMIT:5}
    email: ${EMAIL_RATE_LIMIT:1000}